name: Automatic Binary Release
on:
  push:
    branches: [ main ]
    tags: [ v*.*.* ]

permissions:
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt
          override: true
      - name: Run Build Release
        run: make build-release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release.zip